# Generated by Django 5.1.6 on 2025-02-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='titulo',
        ),
        migrations.AddField(
            model_name='ticket',
            name='acoes',
            field=models.TextField(default=0, verbose_name='Ações'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='analista',
            field=models.CharField(choices=[('leandro_fratel', 'Leandro Fratel'), ('heraclito_teixeira', 'Heráclito Teixeira'), ('camilla_gama', 'Camilla Gama')], default='', max_length=100, verbose_name='Analista'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='causa_raiz',
            field=models.TextField(default=0, verbose_name='Causa Raiz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='codigo_incidente',
            field=models.CharField(default=0, max_length=50, verbose_name='Incidente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='codigo_sx',
            field=models.CharField(default=0, max_length=50, verbose_name='SX'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='grupo_suporte',
            field=models.CharField(choices=[('grupo_operacoes_integradas', 'COI - Grupo de Operações Integradas'), ('operacoes_ibm', 'Operações IBM')], default='', max_length=100, verbose_name='Grupo de Suporte'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='imagens',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/imagens/', verbose_name='Imagens'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='link_alerta',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Alerta'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='problema_apresentado',
            field=models.TextField(default=0, verbose_name='Problema Apresentado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='recurso',
            field=models.CharField(default=0, max_length=100, verbose_name='Recurso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='responsavel',
            field=models.CharField(default=0, max_length=50, verbose_name='Responsável'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='solucao',
            field=models.TextField(default=0, verbose_name='Solução'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado'), ('resolvido', 'Resolvido'), ('em_andamento', 'Em Andamento'), ('designado', 'Designado'), ('em_analise', 'Em Análise'), ('sala_de_crise', 'Sala de Crise')], default='aberto', max_length=50, verbose_name='Status'),
        ),
    ]
